#  _      _                   ____   __      _       __     ___            _        
# (_) ___(_)_ __   __ _  __ _|___ \ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | |/ __| | '_ \ / _` |/ _` | __) | || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | (__| | | | | (_| | (_| |/ __/| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_|\___|_|_| |_|\__, |\__,_|_____| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                 |___/             \_\_|        |___/_/                            
# boot-daemon
- name: boot-daemon | icinga2 daemon should be enabled
  when: icinga2.enabled == true
  service: name=icinga2 enabled=yes

- name: boot-daemon | icinga2 daemon should be disabled
  when: icinga2.enabled == false
  service: name=icinga2 enabled=no

- name: boot-daemon | icinga2 daemon should be started
  when: icinga2.started == true
  service: name=icinga2 state=started

