---
#  _      _                   ____   __      _       __     ___            _        
# (_) ___(_)_ __   __ _  __ _|___ \ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | |/ __| | "_ \ / _` |/ _` | __) | || "_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | (__| | | | | (_| | (_| |/ __/| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_|\___|_|_| |_|\__, |\__,_|_____| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                 |___/             \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | RedHat | Development tools should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "autoconf"
        - "automake"
        - "gcc"
        - "gcc-c++"
        - "gettext"
        - "gettext-devel"
        - "git"
        - "ncurses"
        - "ncurses-devel"
        - "openssl-devel"
        - "patch"
        - "pcre"
        - "pcre-devel"
        - "perl-core"
        - "readline"
        - "readline-devel"

    - name: install-pkg | EPEL repository should be installed
      yum:
        name:  "epel-release"
        state: "present"

    - name: install-pkg | icinga.key should be imported
      rpm_key:
        key:   "http://packages.icinga.org/icinga.key"
        state: "present"

    - name: install-pkg | ICINGA-release.repo should be imported
      shell: >
        wget http://packages.icinga.org/epel/ICINGA-release.repo
      args:
        chdir:   "/etc/yum.repos.d"
        creates: "ICINGA-release.repo"

    - name: install-pkg | Icinga2 and related packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "icinga2"
        - "nagios-plugins-all"
        - "nagios-plugins-nrpe"

    # http://docs.ansible.com/ansible/expect_module.html
    - name: install-pkg | Python egg for the expect module should be installed
      pip:
        name:  "pexpect"
        state: "present"
  when: ansible_os_family == "RedHat"

