---
#  _      _                   ____   __      _       __     ___            _        
# (_) ___(_)_ __   __ _  __ _|___ \ / /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | |/ __| | '_ \ / _` |/ _` | __) | || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | | (__| | | | | (_| | (_| |/ __/| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# |_|\___|_|_| |_|\__, |\__,_|_____| || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
#                 |___/             \_\_|        |___/_/                            
# make-config
- name: make-config | enabled feature list
  register: icinga2_disabled_features
  changed_when: icinga2_disabled_features.rc > 0
  shell: icinga2 feature list | grep '^Disabled '

- name: make-config | some features should be enabled
  when: "'{{ item }}' in icinga2_disabled_features.stdout"
  notify: Restart Icinga2
  shell: icinga2 feature enable {{ item }}
  with_items:
    - command
    - livestatus
    - compatlog
    - perfdata
    - statusdata
    - syslog

- name: make-config | default monitoring should be disabled
  notify: Restart Icinga2
  template:
    src:  etc/icinga2/conf.d/{{ item }}.conf.j2
    dest: /etc/icinga2/conf.d/{{ item }}.conf
  with_items:
    - hosts
    - commands
    - services
    - templates 
    - timeperiods
    - notifications

- name: make-config | /etc/icinga2/conf.d/nodes should be created
  file:
    path: /etc/icinga2/conf.d/nodes
    mode: 0750
    owner: icinga
    group: icinga
    state: directory

- name: make-config | Directories in /etc/icinga2/conf.d/nodes should be exist
  file:
    path: /etc/icinga2/conf.d/nodes/{{ item.name }}
    mode: 0750
    owner: icinga
    group: icinga
    state: directory
  with_items: "{{ icinga2.nodes }}"

- name: make-config | Files in /etc/icinga2/conf.d/nodes should be deployed
  notify: Restart Icinga2
  template:
    src:   etc/icinga2/conf.d/nodes/{{ item.0.name }}/{{ item.1 }}.conf.j2
    dest: /etc/icinga2/conf.d/nodes/{{ item.0.name }}/{{ item.1 }}.conf
    mode: 0640
    owner: icinga
    group: icinga
  with_subelements: 
    - "{{ icinga2.nodes }}"
    - 'file'







